version: '2.0'
services:
  web:
    image: nginx:alpine
    working_dir: {{WORKING_DIR}}
    ports:
      - "80:80"
    links:
      - php
    volumes:
      - {{WORKING_DIR}}:{{WORKING_DIR}}:rw
      - /var/log/nginx/:/etc/nginx/logs/:rw
      - /etc/nginx/:/etc/nignx/:rw
    networks:
      - code-network

  mysql:
    image: mysql:5.7
    expose:
      - "3306"
    environment:
      MYSQL_DATABASE: "{{DB_NAME}}"
      MYSQL_ROOT_PASSWORD: "123123"
    volumes:
      - /var/mysql/data:/var/lib/mysql:rw
    networks:
      - code-network

  php:
    build: ./docker/php
    working_dir: {{WORKING_DIR}}
    expose:
      - "9000"
    links:
      - mysql
      - redis
    volumes:
      - {{WORKING_DIR}}:/data/wwwroot:rw
    networks:
      - code-network

  redis:
    image: redis:alpine
    volumes:
      - /etc/redis:/usr/local/etc/redis:rw
    expose:
      - "6379"
    networks:
      - code-network

networks:
  code-network:
    driver: bridge
